[package]
name = 'example_project'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'devnet'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
Sender = "0xafc93b69bb6960ff6fae5b4d5b6b6790d870a9abeeebe391d0707853a1054969"