[package]
name = "TestExample"
version = "0.0.0"

[dependencies]
MoveStdlib = { local = "/Users/foooox/move/language/move-stdlib", rev = "56ab033cc403b489e891424a629e76f643d4fb6b", addr_subst = { "std" = "0x1" } }

[addresses]
std =  "0x1"
